/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v0/entries/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Entries
     * @description List entries with optional filters
     */
    get: operations['entries_list']
    put?: never
    /**
     * Create Entry
     * @description Create a new entry
     */
    post: operations['entries_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v0/entries/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve Entry
     * @description Retrieve entry by id
     */
    get: operations['entries_retrieve']
    /**
     * Put Entry
     * @description Update an existing entry
     */
    put: operations['entries_update']
    post?: never
    /**
     * Delete Entry
     * @description Delete an existing entry
     */
    delete: operations['entries_destroy']
    options?: never
    head?: never
    /**
     * Patch Entry
     * @description Partially update an existing entry
     */
    patch: operations['entries_partial_update']
    trace?: never
  }
  '/api/v0/titles/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Titles
     * @description List titles with optional filters
     */
    get: operations['titles_list']
    put?: never
    /**
     * Create Title
     * @description Create a title
     */
    post: operations['titles_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v0/titles/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve Title
     * @description Retrieve title by id
     */
    get: operations['titles_retrieve']
    /**
     * Put Title
     * @description Update a title
     */
    put: operations['titles_update']
    post?: never
    /**
     * Delete Title
     * @description Delete a title
     */
    delete: operations['titles_destroy']
    options?: never
    head?: never
    /**
     * Patch Title
     * @description Partially update a title
     */
    patch: operations['titles_partial_update']
    trace?: never
  }
  '/api/v0/users/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Users
     * @description List users with optional filters
     */
    get: operations['users_list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v0/users/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve User
     * @description Retrieve user by id
     */
    get: operations['users_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v0/users/me/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve Me
     * @description Retrieve the current user
     */
    get: operations['users_me_retrieve']
    /**
     * Put Me
     * @description Update the current user
     */
    put: operations['users_me_update']
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Patch Me
     * @description Partially update the current user
     */
    patch: operations['users_me_partial_update']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    Entry: {
      /**
       * Format: uuid
       * @description Unique identifier for this object
       */
      readonly id: string
      /**
       * Format: uuid
       * @description Author of the entry.
       */
      readonly author: string
      /**
       * Format: uuid
       * @description Title of the entry.
       */
      title: string
      /** @description Content of the entry. In tiptap format. */
      content: unknown
      /**
       * Format: date-time
       * @description Date and time this object was created
       */
      readonly created_at: string
      /**
       * Format: date-time
       * @description Date and time this object was last updated
       */
      readonly updated_at: string
    }
    EntryDestroyError: {
      protected_elements: components['schemas']['ProtectedElement'][]
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    EntryRequest: {
      /**
       * Format: uuid
       * @description Title of the entry.
       */
      title: string
      /** @description Content of the entry. In tiptap format. */
      content: unknown
    }
    EntrySerializerError: {
      readonly id: string[]
      readonly author: string[]
      readonly title: string[]
      readonly content: string[]
      readonly created_at: string[]
      readonly updated_at: string[]
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    EntryUpdateRequest: {
      /** @description Content of the entry. In tiptap format. */
      content: unknown
    }
    PaginatedEntryList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['Entry'][]
    }
    PaginatedPublicUserList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['PublicUser'][]
    }
    PaginatedTitleList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['Title'][]
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    PatchedEntryRequest: {
      /**
       * Format: uuid
       * @description Title of the entry.
       */
      title?: string
      /** @description Content of the entry. In tiptap format. */
      content?: unknown
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    PatchedTitleRequest: {
      /**
       * Title
       * @description Name of the title.
       */
      name?: string
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    PatchedUserRequest: {
      first_name?: string
      last_name?: string
    }
    ProtectedElement: {
      /** Format: uuid */
      readonly id: string
      readonly type: string
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    PublicUser: {
      /**
       * Format: uuid
       * @description Unique identifier for this object
       */
      readonly id: string
      /** @description Required. 150 characters or fewer. Letters (lowercase), digits or hyphens only, can't start with letters or hyphens. */
      readonly username: string
      /**
       * Active
       * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
       */
      readonly is_active: boolean
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      readonly is_staff: boolean
      /**
       * Superuser status
       * @description Designates that this user has all permissions without explicitly assigning them.
       */
      readonly is_superuser: boolean
      /**
       * Format: date-time
       * @description Date and time this object was created
       */
      readonly created_at: string
      /**
       * Format: date-time
       * @description Date and time this object was last updated
       */
      readonly updated_at: string
      readonly title_count: number
      readonly entry_count: number
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    Title: {
      /**
       * Format: uuid
       * @description Unique identifier for this object
       */
      readonly id: string
      /**
       * Title
       * @description Name of the title.
       */
      name: string
      /** @description Slug of the title to display in urls. */
      readonly slug: string
      readonly entry_count: number
      /**
       * Format: uuid
       * @description Creator of the title.
       */
      readonly created_by: string
    }
    TitleDestroyError: {
      protected_elements: components['schemas']['ProtectedElement'][]
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    TitleRequest: {
      /**
       * Title
       * @description Name of the title.
       */
      name: string
    }
    TitleSerializerError: {
      readonly id: string[]
      readonly name: string[]
      readonly slug: string[]
      readonly entry_count: string[]
      readonly created_by: string[]
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    User: {
      /**
       * Format: uuid
       * @description Unique identifier for this object
       */
      readonly id: string
      /** @description Required. 150 characters or fewer. Letters (lowercase), digits or hyphens only, can't start with letters or hyphens. */
      readonly username: string
      first_name?: string
      last_name?: string
      /**
       * Email address
       * Format: email
       */
      readonly email: string
      /**
       * Active
       * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
       */
      readonly is_active: boolean
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      readonly is_staff: boolean
      /**
       * Superuser status
       * @description Designates that this user has all permissions without explicitly assigning them.
       */
      readonly is_superuser: boolean
      /**
       * Format: date-time
       * @description Date and time this object was created
       */
      readonly created_at: string
      /**
       * Format: date-time
       * @description Date and time this object was last updated
       */
      readonly updated_at: string
      readonly title_count: number
      readonly entry_count: number
    }
    /** @description Serializes the nested field, doesn't turn the serializer into read-only automatically(should it?) but it is
     *     read only.
     *
     *     GET /api/v1/people/5/
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [7]
     *     }
     *
     *     GET /api/v1/people/5/?include=labels
     *     {
     *         "id": 5,
     *         "first_name": "John",
     *         "last_name": "Doe",
     *         "labels": [
     *             {
     *                 "id": 7,
     *                 "name": "label-name"
     *             }
     *         ]
     *     } */
    UserRequest: {
      first_name?: string
      last_name?: string
    }
    UserSerializerError: {
      readonly id: string[]
      readonly username: string[]
      readonly first_name: string[]
      readonly last_name: string[]
      readonly email: string[]
      readonly is_active: string[]
      readonly is_staff: string[]
      readonly is_superuser: string[]
      readonly created_at: string[]
      readonly updated_at: string[]
      readonly title_count: string[]
      readonly entry_count: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  entries_list: {
    parameters: {
      query?: {
        /** @description Unique identifier for this object */
        author?: string
        created_at?: string
        created_at__gte?: string
        created_at__lte?: string
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A page number within the paginated result set. */
        page?: number
        /** @description A search term. */
        search?: string
        /** @description Unique identifier for this object */
        title?: string
        updated_at?: string
        updated_at__gte?: string
        updated_at__lte?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedEntryList']
        }
      }
    }
  }
  entries_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryRequest']
        'application/x-www-form-urlencoded': components['schemas']['EntryRequest']
        'multipart/form-data': components['schemas']['EntryRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Entry']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntrySerializerError']
        }
      }
    }
  }
  entries_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Entry']
        }
      }
    }
  }
  entries_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EntryUpdateRequest']
        'application/x-www-form-urlencoded': components['schemas']['EntryUpdateRequest']
        'multipart/form-data': components['schemas']['EntryUpdateRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Entry']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntrySerializerError']
        }
      }
    }
  }
  entries_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryDestroyError']
        }
      }
    }
  }
  entries_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedEntryRequest']
        'application/x-www-form-urlencoded': components['schemas']['PatchedEntryRequest']
        'multipart/form-data': components['schemas']['PatchedEntryRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Entry']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntrySerializerError']
        }
      }
    }
  }
  titles_list: {
    parameters: {
      query?: {
        created_at?: string
        created_at__gte?: string
        created_at__lte?: string
        name?: string
        name__contains?: string
        name__icontains?: string
        name__iexact?: string
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A page number within the paginated result set. */
        page?: number
        /** @description A search term. */
        search?: string
        updated_at?: string
        updated_at__gte?: string
        updated_at__lte?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedTitleList']
        }
      }
    }
  }
  titles_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TitleRequest']
        'application/x-www-form-urlencoded': components['schemas']['TitleRequest']
        'multipart/form-data': components['schemas']['TitleRequest']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Title']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TitleSerializerError']
        }
      }
    }
  }
  titles_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Title']
        }
      }
    }
  }
  titles_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TitleRequest']
        'application/x-www-form-urlencoded': components['schemas']['TitleRequest']
        'multipart/form-data': components['schemas']['TitleRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Title']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TitleSerializerError']
        }
      }
    }
  }
  titles_destroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TitleDestroyError']
        }
      }
    }
  }
  titles_partial_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedTitleRequest']
        'application/x-www-form-urlencoded': components['schemas']['PatchedTitleRequest']
        'multipart/form-data': components['schemas']['PatchedTitleRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Title']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TitleSerializerError']
        }
      }
    }
  }
  users_list: {
    parameters: {
      query?: {
        created_at?: string
        created_at__gte?: string
        created_at__lte?: string
        is_active?: boolean
        is_staff?: boolean
        is_superuser?: boolean
        /** @description Which field to use when ordering the results. */
        ordering?: string
        /** @description A page number within the paginated result set. */
        page?: number
        /** @description A search term. */
        search?: string
        updated_at?: string
        updated_at__gte?: string
        updated_at__lte?: string
        username__icontains?: string
        username__iexact?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedPublicUserList']
        }
      }
    }
  }
  users_retrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublicUser']
        }
      }
    }
  }
  users_me_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  users_me_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['UserRequest']
        'application/x-www-form-urlencoded': components['schemas']['UserRequest']
        'multipart/form-data': components['schemas']['UserRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserSerializerError']
        }
      }
    }
  }
  users_me_partial_update: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUserRequest']
        'application/x-www-form-urlencoded': components['schemas']['PatchedUserRequest']
        'multipart/form-data': components['schemas']['PatchedUserRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserSerializerError']
        }
      }
    }
  }
}
