# Generated by Django 5.1 on 2024-10-10 01:25

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_entry_delete_delete_title_delete_delete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time this object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Date and time this object was last updated"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        help_text="Invitation code.",
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(8),
                        ],
                    ),
                ),
                (
                    "used_by",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        help_text="User who used the invitation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of the invitation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
