# Generated by Django 5.1 on 2024-10-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_invitationevent_invitation_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
