# Generated by Django 5.1 on 2024-10-13 08:55

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_vote_voteevent_vote_insert_insert_vote_update_update_and_more"),
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time this object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Date and time this object was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Bookmark",
                "verbose_name_plural": "Entry Bookmarks",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EntryBookmarkEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time this object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date and time this object was last updated"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(fields=("user", "entry"), name="unique_user_entry_vote"),
        ),
        migrations.AddField(
            model_name="entrybookmark",
            name="entry",
            field=models.ForeignKey(
                help_text="Entry that was bookmarked.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_bookmarks",
                to="core.entry",
            ),
        ),
        migrations.AddField(
            model_name="entrybookmark",
            name="user",
            field=models.ForeignKey(
                help_text="User who bookmarked.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entrybookmarkevent",
            name="entry",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="Entry that was bookmarked.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.entry",
            ),
        ),
        migrations.AddField(
            model_name="entrybookmarkevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="entrybookmarkevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.entrybookmark",
            ),
        ),
        migrations.AddField(
            model_name="entrybookmarkevent",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="User who bookmarked.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="entrybookmark",
            constraint=models.UniqueConstraint(fields=("user", "entry"), name="unique_user_entry_bookmark"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="entrybookmark",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_entrybookmarkevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id") VALUES (NEW."created_at", NEW."entry_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="e0c70b881d2ef3354927a94ffe947e80fa1a24b6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_fa3aa",
                    table="core_entrybookmark",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="entrybookmark",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_entrybookmarkevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id") VALUES (NEW."created_at", NEW."entry_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."user_id"); RETURN NULL;',
                    hash="f57e709b7ea838e9824bdc387c782635c17e2372",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_781ea",
                    table="core_entrybookmark",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="entrybookmark",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_entrybookmarkevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id") VALUES (OLD."created_at", OLD."entry_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."user_id"); RETURN NULL;',
                    hash="03387b740cca0dedfa31a7233684fe194786b9a0",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_0afb6",
                    table="core_entrybookmark",
                    when="AFTER",
                ),
            ),
        ),
    ]
