# Generated by Django 5.1 on 2024-11-08 20:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_titlebookmark_titlebookmarkevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="user",
            name="delete_delete",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("READER", "Reader"),
                    ("NEW_RECRUIT", "New Recruit"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("TRUSTED", "Trusted"),
                ],
                default="NEW_RECRUIT",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="role",
            field=models.CharField(
                choices=[
                    ("READER", "Reader"),
                    ("NEW_RECRUIT", "New Recruit"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("TRUSTED", "Trusted"),
                ],
                default="NEW_RECRUIT",
                max_length=11,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="db2006d18a787eb409ac8a5fcf848551a43aa456",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_45de6",
                    table="core_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "updated_at", "username") VALUES (NEW."created_at", NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_login", NEW."last_name", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."updated_at", NEW."username"); RETURN NULL;',
                    hash="1d61338d85dc01cc55328d0ab560475e9ec70391",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6ccff",
                    table="core_user",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "updated_at", "username") VALUES (OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."updated_at", OLD."username"); RETURN NULL;',
                    hash="4bfc90a1ad3a80bdbfc78ef803efd760058b625c",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1425a",
                    table="core_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
