# Generated by Django 5.1 on 2025-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_entry_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(
                help_text="Name of the title.",
                max_length=255,
                unique=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="titleevent",
            name="name",
            field=models.CharField(help_text="Name of the title.", max_length=255, verbose_name="Title"),
        ),
    ]
