# Generated by Django 5.1 on 2025-03-30 19:13

import core.managers.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_title_name_alter_titleevent_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.managers.user.UserManager()),
            ],
        ),
    ]
