# Generated by Django 5.1 on 2025-04-27 21:55

import common.validators.allowed_characters
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters (lowercase), digits, dots or hyphens only, must start with letters.",
                max_length=150,
                unique=True,
                validators=[
                    common.validators.allowed_characters.AllowedCharactersValidator(
                        allowed_characters="abcdefghijklmnopqrstuvwxyz0123456789-_.",
                        allowed_first="abcdefghijklmnopqrstuvwxyz",
                        allowed_last="abcdefghijklmnopqrstuvwxyz0123456789-_.",
                        message="Username must start with a lowercase letter, and can only contain lowercase letters, digits, hyphens, underscores, and periods.",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters (lowercase), digits, dots or hyphens only, must start with letters.",
                max_length=150,
                validators=[
                    common.validators.allowed_characters.AllowedCharactersValidator(
                        allowed_characters="abcdefghijklmnopqrstuvwxyz0123456789-_.",
                        allowed_first="abcdefghijklmnopqrstuvwxyz",
                        allowed_last="abcdefghijklmnopqrstuvwxyz0123456789-_.",
                        message="Username must start with a lowercase letter, and can only contain lowercase letters, digits, hyphens, underscores, and periods.",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
