# Generated by Django 5.1 on 2024-10-09 23:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_title_and_entry_events"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="entry",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_entryevent" ("author_id", "content", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title_id", "updated_at") VALUES (OLD."author_id", OLD."content", OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."title_id", OLD."updated_at"); RETURN NULL;',
                    hash="7bc7f50dfd09ad073f624e7e705c15a44ae83905",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_8707a",
                    table="core_entry",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="title",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_titleevent" ("created_at", "created_by_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "updated_at") VALUES (OLD."created_at", OLD."created_by_id", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."slug", OLD."updated_at"); RETURN NULL;',
                    hash="a9e7d24f5484f4eb8b94cdf6da8cee1d8f5b111a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_bcc62",
                    table="core_title",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="user",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_userevent" ("created_at", "date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_login", "last_name", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "username") VALUES (OLD."created_at", OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_login", OLD."last_name", OLD."password", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."username"); RETURN NULL;',
                    hash="ce792ee2812ca68f32e367adbef02027b5f94dda",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1425a",
                    table="core_user",
                    when="AFTER",
                ),
            ),
        ),
    ]
