# Generated by Django 5.1 on 2024-10-13 02:36

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_make_user_emails_unique"),
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time this object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="Date and time this object was last updated"
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("UPVOTE", "Upvote"), ("DOWNVOTE", "Downvote")], help_text="Vote", max_length=8
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="Entry that was voted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who voted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VoteEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this object",
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time this object was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date and time this object was last updated"),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("UPVOTE", "Upvote"), ("DOWNVOTE", "Downvote")], help_text="Vote", max_length=8
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="Entry that was voted.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="core.entry",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="core.vote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="User who voted.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="vote",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_voteevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id", "vote") VALUES (NEW."created_at", NEW."entry_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."user_id", NEW."vote"); RETURN NULL;',
                    hash="a222596c6e02801e3b4503d6dd79a7468284f7c7",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0dac6",
                    table="core_vote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="vote",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_voteevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id", "vote") VALUES (NEW."created_at", NEW."entry_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."user_id", NEW."vote"); RETURN NULL;',
                    hash="f042d9dc448a511ea4984b60522801fd3066f7ab",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_37119",
                    table="core_vote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="vote",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_voteevent" ("created_at", "entry_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "user_id", "vote") VALUES (OLD."created_at", OLD."entry_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."user_id", OLD."vote"); RETURN NULL;',
                    hash="aed4e4bde6a5557642115837ac381626f9145510",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_c4b1d",
                    table="core_vote",
                    when="AFTER",
                ),
            ),
        ),
    ]
